# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.fizz_buzz_service:
        class: AppBundle\Service\FizzBuzzService
        arguments: []
